version: '3'

services:
    newrelic-apm-daemon:
        image: newrelic/php-daemon:9.12.0
        ports:
            - "31339:31339"
    app:
        build:
            context: .
            args:
                - NEW_RELIC_LICENSE_KEY=
                - NEW_RELIC_APPNAME="TestNewRelic - Production"
                - NEW_RELIC_DAEMON_ADDRESS="newrelic-apm-daemon:31339"

        container_name: newreliclaravel
        image: mahmudz/newreliclaravel
        tty: true
        restart: always
        volumes:
            - ./:/var/www/html/
        depends_on:
            - db
            - newrelic-apm-daemon
        networks:
            - app-network
    nginx:
        container_name: newrelicnginx
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        container_name: newreliclaraveldb
        image: mysql:5.7.32
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
